Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MVSPages.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MVSPages.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MVSPages.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

Pages/SubmitJob.cshtml.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.IO;
using System.Threading.Tasks;
using System.Net.Sockets;
using System.Text;
using System.Text.Json;

namespace MVSPages.Pages
{
    public class HostSettings
    {
        public string Host { get; set; }
        public string Port { get; set; }
        public string HostHttpUrl { get; set; }
    }

    public class SubmitJobModel : PageModel
    {
        private IWebHostEnvironment _environment;

        private static HostSettings? hostSettings = null;

        private string InvalidateId { get; set; }

        public SubmitJobModel(IWebHostEnvironment environment)
        {
            _environment = environment;
            //_httpContextAccessor = httpContextAccessor;
            if (hostSettings == null)
            {
                JclText = string.Empty;
                var file = Path.Combine(_environment.ContentRootPath, "", "hostsettings.json");

                string json = System.IO.File.ReadAllText(file);
                hostSettings =
                    JsonSerializer.Deserialize<HostSettings>(json);

            }


            Host = hostSettings.Host;
            Port = hostSettings.Port;
            //HostHttpUrl = hostSettings.HostHttpUrl;
        }

        [ViewData]
        public string JclText
        {
            get; set;
        }

        private void SetInvalidateId()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("InvalidateId")))
            {
                HttpContext.Session.SetString("InvalidateId", "1");
                HostHttpUrl = hostSettings.HostHttpUrl + "?InvalidateId=1";
            }
            else
            {
                int iVal = int.Parse(HttpContext.Session.GetString("InvalidateId"));
                iVal++;
                HostHttpUrl = hostSettings.HostHttpUrl + "?InvalidateId=" + iVal.ToString();

            }

        }
        public void OnGet()
        {
            SetInvalidateId();
        }

        public string HostHttpUrl { get; set; }
        [BindProperty]
        public IFormFile Upload { get; set; }
        public async Task OnPostUploadFileAsync()
        {
            var file = Path.Combine(_environment.ContentRootPath, "upload", Upload.FileName);
            using (var fileStream = new FileStream(file, FileMode.Create))
            {
                await Upload.CopyToAsync(fileStream);
            }

            JclText = System.IO.File.ReadAllText(file).Trim();
            HttpContext.Session.SetString("Jcl", JclText);

            SetInvalidateId();

        }

        [BindProperty]
        public string Host { get; set; }
        [BindProperty]
        public string Port { get; set; }

        [BindProperty]
        public string TextValue { get; set; }

        public void OnPostSubmitJcl()
        {
            using TcpClient tcpClient = new TcpClient();
            tcpClient.Connect(Host, int.Parse(Port));

            using NetworkStream netStream = tcpClient.GetStream();

            // Send some data to the peer.
            JclText = TextValue;
            if (JclText != null && JclText != string.Empty)
            {
                byte[] sendBuffer = Encoding.ASCII.GetBytes(JclText);
                netStream.Write(sendBuffer);

            }

            SetInvalidateId();
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVSPages</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVSPages.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">MVSPages</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/SubmitJob">Submit Job</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVSPages - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Pages/SubmitJob.cshtml
@page
@model MVSPages.Pages.SubmitJobModel
@{
  ViewData["Jcl"] = string.Empty;
}

<style>
  .btn {
    background-color: DodgerBlue;
    border: none;
    color: white;
    padding: 8px 8px;
    cursor: pointer;
    font-size: 10px;
  }

  /* Darker background on mouse-over */
  .btn:hover {
    background-color: RoyalBlue;
  }

  .fil {
    cursor: pointer;
    font-size: 10px;
  }

  textarea#styled {
    width: 600px;
    height: 270px;
    border: 3px solid #cccccc;
    padding: 5px;
    font-family: Tahoma, sans-serif;
    font-size: 10px;
    /*background-image: url(bg.gif);*/
    background-position: bottom right;
    background-repeat: no-repeat;
  }

  * {
    box-sizing: border-box;
  }

  /* Create two equal columns that floats next to each other */
  .column {
    float: left;
    width: 50%;
    padding: 10px;
    height: 300px;
    /* Should be removed. Only for demonstration */
  }

  /* Clear floats after the columns */
  .row:after {
    content: "";
    display: table;
    clear: both;
  }

  .grid-container {
    display: grid;
    grid-template-columns: auto auto;
    background-color: #2196F3;
    padding: 10px;
  }

  .grid-item {
    background-color: rgba(255, 255, 255, 0.8);
    border: 1px solid rgba(0, 0, 0, 0.8);
    padding: 20px;
    font-size: 30px;

  }

  .form-inline {
    display: flex;
    flex-flow: row wrap;
    align-items: center;
  }

  /* Add some margins for each label */
  .form-inline label {
    margin: 5px 10px 5px 0;
    font-size: 10px;

  }

  /* Style the input fields */
  .form-inline input {
    vertical-align: middle;
    margin: 5px 10px 5px 0;
    padding: 10px;
    font-size: 10px;
    background-color: #fff;
    border: 1px solid #ddd;
  }

  /* Style the submit button */
  .form-inline button {
    padding: 10px 20px;
    background-color: dodgerblue;
    border: 1px solid #ddd;
    font-size: 10px;
    color: white;
  }

  .form-inline button:hover {
    background-color: royalblue;
  }
</style>

@section Scripts {
<script>
  const element = document.getElementById("btnSub2");
  element.addEventListener("click", function () {
    document.getElementById("TextValue").value = document.getElementById("styled").value;
  });
</script>
}

<h1>Submit Job</h1>
<div class="grid-container">
  <div class="grid-item">
    <form method="post" enctype="multipart/form-data" asp-page-handler="UploadFile">
      <input type="file" asp-for="Upload" class="fil" />
      <input type="submit" value="Upload File" class="btn" />
    </form>
  </div>
  <div class="grid-item">
    <form method="post" asp-page-handler="SubmitJcl" class="form-inline">
      <label for="Host">Host:</label>
      <input asp-for="Host" id="Host" readonly="true" />
      <label for="Port">Port:</label>
      <input asp-for="Port" id="Port" readonly="true"/>
      <input type="hidden" asp-for="TextValue" id="TextValue"  />

      <button type="submit" class="btn" id="btnSub2">Submit Jcl</button>
    </form>

  </div>
  <div class="grid-item">
    <textarea id="styled">@Model.JclText</textarea>
  </div>
  <div class="grid-item">
    <iframe src="@Model.HostHttpUrl" height="270px" width="600px" frameborder="0"
      marginheight="20" marginwidth="35" scrolling="auto">
    </iframe>
  </div>
</div>